feature footer
Knight-H/e-sticker-frontend pull request #1
Opened 2020-09-19 05:05 UTC by codenuk

2020-09-19 05:17 UTC, Knight-H requested changes
## Things to Improve
- [ ] Remove package.json in github tracking stage
- [x] In `footer/index.js` , `withRouter` is not used, why did you include?
- [x] In `footer/index.js`, WTF WHERE IS QR CODE? WHERE IS LINE, FB, EMAIL? WTF WHY IS IT IN SVG????
- [x] In `footer/index.js`, style name should be camelCase.
- [x] In `footer/index.js`, `styles.footer` should case name to something like `footerBar` or something for more specific. 
- [x] In `footer/index.js`, `<li>` `title_bold` should be `<b>` 


## Things to Note
- FooterComponent in App.js is new in every page??

2020-09-20 10:03 UTC, codenuk commented
@Knight-H Hello i edit code in page footer plz check

2020-09-20 15:33 UTC, Knight-H requested changes
Make sure your code is DRY before submitting for review.

2020-09-20 15:33 UTC, Knight-H commented on src/components/footer/index.js
> +                <ul className={styles.lisrContract}>
```suggestion
                <ul className={styles.listContact}>
```

2020-09-20 15:33 UTC, Knight-H commented on src/components/footer/index.js
> +                <BannerFooter  />
Why is this here this time? Last time it was imported by css isn't it?

2020-09-20 15:33 UTC, Knight-H commented on src/components/footer/index.module.scss
> +    .lisrContract {
```suggestion
    .listContact {
```

2020-09-20 15:33 UTC, Knight-H commented on src/components/footer/index.module.scss
> +    flex-direction: row;
```suggestion
```

By default it's row

2020-09-20 15:33 UTC, Knight-H commented on src/components/footer/index.module.scss
> +            }
WHY THE HELL IS THIS CLASS COPIED AGAIN AND AGAIN? 3 FUCKING TIMES?

2020-09-20 15:33 UTC, Knight-H commented on src/components/footer/index.module.scss
> +            position: relative;
`.squareLine` and `squareFace` is not so fucking different. the only thing different is the background-color?  Use class the way it should be. STOP REPEATING YOURSELF OVER AND OVER. CLEAN IT.

2020-09-20 15:33 UTC, Knight-H commented
Oh, and also try to spell English correctly

2020-09-21 01:24 UTC, codenuk commented
i update 3 page na. 
   1) footer but i think i must edit this page to responsive to day.
   2) upload file page
   3) approve page => miss 2 componant because each of componant is P.Donut

2020-09-21 03:22 UTC, merged