Feature update css nuk
Knight-H/e-sticker-frontend pull request #11
Opened 2020-10-03 03:13 UTC by codenuk

2020-10-03 05:59 UTC, SorawitSiri commented on src/components/navbar/index.js
> +                    <li><button><Link to="/form_step_shopping">สั่งทำสติกเกอร์</Link></button></li>
Link ต้องทำใช้ history ของ react หรือป่าว

2020-10-03 06:01 UTC, SorawitSiri commented on src/components/navbar/index.js
> +                    <li><button><Link to="/form_step_shopping">สั่งทำสติกเกอร์</Link></button></li>
ใช้ button onClick=history.push(????)

2020-10-03 06:04 UTC, SorawitSiri reviewed
Must edit button for Link.

2020-10-03 06:08 UTC, Knight-H requested changes

2020-10-03 06:08 UTC, Knight-H commented on src/components/admin-login/index.js
> +                <TextInput className="inputText" name="email" />
Not field?

2020-10-03 06:08 UTC, Knight-H commented on src/components/approve-layout/index.js
> +                <LabelSatus status={fakeAPI[0].statusOrder}/>
LABELSATUS?

2020-10-03 06:08 UTC, Knight-H commented on src/components/common/formik-password-input.js
> +            <input type='password' {...field} {...props} />
just use field

2020-10-03 06:08 UTC, Knight-H commented on src/components/common/formik-radio-input.js
> +import { useField } from 'formik';
use `<Field/>`

2020-10-03 06:08 UTC, Knight-H commented on src/components/group-delivery-payment/index.module.scss
> +    .containInformationCustomer{
container

2020-10-03 06:08 UTC, Knight-H commented on src/components/group-delivery-payment/index.module.scss
> +    .containInformation {
container

2020-10-03 06:08 UTC, Knight-H commented on src/components/helper.js
> +export const validateFiledID = (value) => {
file

2020-10-03 06:08 UTC, Knight-H commented on src/components/helper.js
> +export function setNestedObjectValues(
now no need

2020-10-03 06:08 UTC, Knight-H commented on src/components/home-member/index.module.scss
> +.contain {
container

2020-10-03 06:08 UTC, Knight-H commented on src/components/home-member/index.module.scss
> +  }
formatting

2020-10-03 06:08 UTC, Knight-H commented on src/components/home-member/index.module.scss
> +    .contain {
container

2020-10-03 06:08 UTC, Knight-H commented on src/components/home/index.js
> +                        <Link to="/form_step_shopping"><b>สั่งซื้อสินค้า</b></Link>
???

2020-10-03 06:08 UTC, Knight-H commented on src/components/navbar/index.js
> +                    <li><button><Link to="/form_step_shopping">สั่งทำสติกเกอร์</Link></button></li>
customize

2020-10-03 06:08 UTC, Knight-H commented on src/components/order-1-product-config/index.js
> +                        <SelectInput name="quantityStricker" validate={validateQuantityFiledID}>
Field

2020-10-03 06:08 UTC, Knight-H commented on src/components/order-1-product-config/index.js
>                      </button>
type="submit"

2020-10-03 06:08 UTC, Knight-H commented on src/components/order-1-product-config/index.js
> +                                setTouched(setNestedObjectValues(values, true))
NO NEED

2020-10-03 06:08 UTC, Knight-H commented on src/components/preview-image/index.js
> +                <div className={styles.groupBtn}>
Btn or Button

2020-10-03 06:08 UTC, Knight-H commented on src/components/preview-image/index.js
> +                    <button type="button" className={styles.btnCustomWidth}>อัพโหลดไฟล์</button>
btn in front or at the back

2020-10-03 06:08 UTC, Knight-H commented on src/components/upload-file/index.js
> +
cahnge to API

2020-10-05 13:26 UTC, SorawitSiri approved these changes, later dismissed

2020-10-05 16:31 UTC, SorawitSiri approved these changes

2020-10-06 03:26 UTC, Knight-H approved these changes

2020-10-06 03:26 UTC, merged